CONFIG_I2C=y
CONFIG_I2C_NRFX_TRANSFER_TIMEOUT=25
CONFIG_GPIO=y
CONFIG_WATCHDOG=y
CONFIG_REBOOT=y
CONFIG_POWEROFF=y
CONFIG_BT=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_PERIPHERAL=n
CONFIG_BT_OBSERVER=n
CONFIG_HWINFO=y
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
