CONFIG_MULTITHREADING=y
CONFIG_I2C=y
CONFIG_I2C_NRFX_TRANSFER_TIMEOUT=25
CONFIG_HWINFO=y
CONFIG_POWEROFF=y
# DK UART20 uses P1.4/P1.5, which belong to the unpowered FDC bus here.
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
